FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

# Etapa final
FROM node:18-slim
WORKDIR /app
COPY --from=build /app .
EXPOSE 3000
CMD ["node", "server.js"]
